project:
  type: website
  output-dir: docs

website:
  title: "Jamie Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: US Generation.qmd
        text: US Generation
      - href: Fitness Data.qmd
        text: Fitness Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

