project:
  type: website
  output-dir: docs

website:
  title: "Jamie Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - US Generation.qmd
      - Fitness Data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

