---
title: "ABOUT"
#image: 
about: 
  template: jolla
  image-shape: round
  image-width: 15em
  links: 
    - text: Email
      icon: envelope
      href: mailto:jamiek101699@gmail.com
    - text: GitHub
      icon: github
      href: https://github.com/jamiekim1
    - text: Mobile (780-996-5281)
      icon: telephone
---

 **Jamie Kim** <br>
 **Age: 23** <br>
 **Student at the University of Alberta** <br>
 **4th Year Finance student** <br>

Thank you for visiting my profile! This is a showcase of my different coding projects ranging from finance related applications to data analytics on various topics. These projects cover various technical skills like machine learning, web scraping, predictive analysis, natural language processing, and statistical analysis. Thank you for taking the time to explore my projects and feel free to ask me any questions!

I am currently a Finance student studying at the University of Alberta School of Business. I am always eager to learn, improve, and hone my technical skills. I am passionate about trading, risk management, portfolio management, and data analytics. I believe in continued learning and application of my knowledge and skills in a practical manner. My goal is to grow and take on new challenges as I build a career in the finance industry.
